CREATE TABLE IF NOT EXISTS setores (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL UNIQUE,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS salas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  setor_id INT NOT NULL,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_salas_setor
    FOREIGN KEY (setor_id) REFERENCES setores(id)
    ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT unq_salas_setor_nome
    UNIQUE (setor_id, nome)
) ENGINE=InnoDB;

-- DOWN (rollback)
-- DROP TABLE salas;
-- DROP TABLE setores;
